/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FunComidas;
import datos.Comidas;
import javax.swing.ButtonGroup;

/**
 *
 * @author USER1
 */
public class BebidasUI extends javax.swing.JInternalFrame {
private String accion = "guardar";
    private final ButtonGroup grupoComidas; // ButtonGroup para agrupar los radio buttons
    private final FunComidas funComidas; // Declaración de la variable
    private final DefaultTableModel modeloTabla; // Modelo de tabla para platos

    /**
     * Creates new form BebidasUI
     */
    public BebidasUI() {
        initComponents();
        inhabilitar();

        
        grupoComidas = new ButtonGroup(); // Inicializar el ButtonGroup
        funComidas = new FunComidas(); // Puedes ajustar la inicialización según tus necesidades
        
        // Agregar los radio buttons al ButtonGroup
        grupoComidas.add(rbtnAguas);
        grupoComidas.add(rbtnJugos);
        grupoComidas.add(rbtnRefrescos);
        grupoComidas.add(rbtnCervezas);
        grupoComidas.add(rbtnVinos);
        
        modeloTabla = (DefaultTableModel) tblBebidas.getModel();
        modeloTabla.addColumn("idplato");
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("descripcion");
        modeloTabla.addColumn("observacion");
        modeloTabla.addColumn("valor");
        modeloTabla.addColumn("stock");
        modeloTabla.addColumn("estado");  
        mostrar("");
    
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBebidas = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTotalBebidas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rbtnCervezas = new javax.swing.JRadioButton();
        rbtnVinos = new javax.swing.JRadioButton();
        cboAguas = new javax.swing.JComboBox<>();
        cboJugos = new javax.swing.JComboBox<>();
        rbtnAguas = new javax.swing.JRadioButton();
        cboRefrescos = new javax.swing.JComboBox<>();
        rbtnJugos = new javax.swing.JRadioButton();
        cboCervezas = new javax.swing.JComboBox<>();
        rbtnRefrescos = new javax.swing.JRadioButton();
        cboVinos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtidplato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel = new javax.swing.JPanel();
        jLabel = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelP = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jlabel2 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        brnNuevo = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        setTitle("COMIDAS RAPIDAS - BEBIDAS");
        setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("BEBIDAS");

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        tblBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Selección", "Nombre", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBebidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBebidasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBebidas);

        jLabel7.setText("INGRESO BEBIDAS");

        btnSalir.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblTotalBebidas.setText("Bebidas Seleccionadas");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(343, 343, 343)
                                .addComponent(btnSalir)
                                .addGap(0, 125, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotalBebidas)
                        .addGap(34, 34, 34))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(28, 28, 28))
                    .addComponent(btnSalir, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(lblTotalBebidas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        rbtnCervezas.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnCervezas.setForeground(new java.awt.Color(51, 51, 51));
        rbtnCervezas.setText("Cervezas");
        rbtnCervezas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCervezasActionPerformed(evt);
            }
        });

        rbtnVinos.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnVinos.setForeground(new java.awt.Color(51, 51, 51));
        rbtnVinos.setText("Vinos");
        rbtnVinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnVinosActionPerformed(evt);
            }
        });

        cboAguas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agua Natural", "Agua con Gas Perrier", "Agua de Purificada Aquafina", "Agua Alcalina Essential", "Agua de Coco Natural", "Agua Mineral San Pelegrino", " " }));

        cboJugos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugo de Zanahoria", "Jugo de Manzana", "Jugo de Piña", "Jugo de Toronja", "Jugo de Maracuya", " " }));

        rbtnAguas.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnAguas.setForeground(new java.awt.Color(51, 51, 51));
        rbtnAguas.setText("Aguas");
        rbtnAguas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAguasActionPerformed(evt);
            }
        });

        cboRefrescos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Coca-Cola", "Coca-Cola Ligth", "Pepsi", "Sprite", "Sprite Zero", "7UP", "Fanta", "Red Bull", "Monster Cola", " " }));

        rbtnJugos.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnJugos.setForeground(new java.awt.Color(51, 51, 51));
        rbtnJugos.setText("Jugos");
        rbtnJugos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnJugosActionPerformed(evt);
            }
        });

        cboCervezas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilsener", "Club Verde", "Club Roja", "Heineken", "Modelo", "Corona Extra", "Stela Artois", "Budweiser" }));

        rbtnRefrescos.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnRefrescos.setForeground(new java.awt.Color(51, 51, 51));
        rbtnRefrescos.setText("Regrescos");
        rbtnRefrescos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnRefrescosActionPerformed(evt);
            }
        });

        cboVinos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cabernet Sauvignon", "Merlot", "Pino Noir", "Syrah", "Malbec", "Chardonnay" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnVinos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboVinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnCervezas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboCervezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnRefrescos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnJugos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboJugos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(rbtnAguas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboAguas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboAguas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnAguas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboJugos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnJugos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboRefrescos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnRefrescos))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCervezas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnCervezas))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboVinos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnVinos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel11.setText("INGRESO PEDIDOS");

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Gestión Bebidas");

        jLabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(51, 51, 51));
        jLabel.setText("Nombre:");

        jLabelD.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabelD.setForeground(new java.awt.Color(51, 51, 51));
        jLabelD.setText("Descripción:");

        jLabelP.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabelP.setForeground(new java.awt.Color(51, 51, 51));
        jLabelP.setText("Precio:");

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));

        txtDescripcion.setBackground(new java.awt.Color(204, 204, 204));

        txtPrecio.setBackground(new java.awt.Color(204, 204, 204));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Observación:");

        txtObservaciones.setBackground(new java.awt.Color(204, 204, 204));

        jlabel2.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jlabel2.setForeground(new java.awt.Color(51, 51, 51));
        jlabel2.setText("Estado:");

        txtEstado.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Stock:");

        txtStock.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addComponent(jLabelP)
                        .addGap(43, 43, 43)
                        .addComponent(txtPrecio))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelD)
                            .addComponent(jLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(txtDescripcion)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addComponent(jlabel2)
                        .addGap(41, 41, 41)
                        .addComponent(txtEstado))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObservaciones)
                            .addComponent(txtStock))))
                .addContainerGap())
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelD)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelP)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel2)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        brnNuevo.setText("Nuevo");
        brnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnNuevoActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(brnNuevo)
                        .addGap(97, 97, 97)
                        .addComponent(btnGuardar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(txtidplato))
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimpiar)
                        .addGap(81, 81, 81))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtidplato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLimpiar)
                        .addComponent(btnGuardar))
                    .addComponent(brnNuevo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(437, 437, 437)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            FunComidas func = new FunComidas();
            modelo = func.mostrar(buscar);

            tblBebidas.setModel(modelo);
            lblTotalBebidas.setText("Total Registros " + Integer.toString(func.totalRegistros));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    //Metodo para ocultar las columnas de la tabla
    void ocultarColumnas() {
        tblBebidas.getColumnModel().getColumn(0).setMaxWidth(0);
        tblBebidas.getColumnModel().getColumn(0).setMinWidth(0);
        tblBebidas.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    void inhabilitar() {
        txtidplato.setVisible(false);
        txtNombre.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtObservaciones.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtStock.setEnabled(false);
        txtEstado.setEnabled(false);
        
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(false);
    
        txtidplato.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtObservaciones.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtEstado.setText("");
    
    }
    void habilitar() {
        txtidplato.setVisible(false);
        txtNombre.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtObservaciones.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtStock.setEnabled(true);
        txtEstado.setEnabled(true);
        
        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnLimpiar.setEnabled(true);
    
        txtidplato.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtObservaciones.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtEstado.setText("");
    } 

    private void rbtnAguasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAguasActionPerformed
        // TODO add your handling code here:
        //lógica cuando se selecciona la opción Agua
        if (rbtnAguas.isSelected()) {
            mostrarMensaje("Aguas seleccionada");
            cboAguas.setEnabled(true);
            cboJugos.setEnabled(false);
            cboRefrescos.setEnabled(false);
            cboCervezas.setEnabled(false);
            cboVinos.setEnabled(false);  
        }
    }//GEN-LAST:event_rbtnAguasActionPerformed

    private void rbtnJugosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnJugosActionPerformed
        // TODO add your handling code here:
        if (rbtnJugos.isSelected()) {
            mostrarMensaje("Jugos seleccionados");
            cboAguas.setEnabled(false);
            cboJugos.setEnabled(true);
            cboRefrescos.setEnabled(false);
            cboCervezas.setEnabled(false);
            cboVinos.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnJugosActionPerformed

    private void rbtnRefrescosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnRefrescosActionPerformed
        // TODO add your handling code here:
        if (rbtnAguas.isSelected()) {
            mostrarMensaje("Refrescos seleccionados");
            cboAguas.setEnabled(false);
            cboJugos.setEnabled(false);
            cboRefrescos.setEnabled(true);
            cboCervezas.setEnabled(false);
            cboVinos.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnRefrescosActionPerformed

    private void rbtnCervezasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCervezasActionPerformed
        // TODO add your handling code here:
        if (rbtnAguas.isSelected()) {
            mostrarMensaje("Cervezas seleccionadas");
            cboAguas.setEnabled(false);
            cboJugos.setEnabled(false);
            cboRefrescos.setEnabled(false);
            cboCervezas.setEnabled(true);
            cboVinos.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnCervezasActionPerformed

    private void rbtnVinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnVinosActionPerformed
        // TODO add your handling code here:
        if (rbtnAguas.isSelected()) {
            mostrarMensaje("Vinos seleccionados");
            cboAguas.setEnabled(false);
            cboJugos.setEnabled(false);
            cboRefrescos.setEnabled(false);
            cboCervezas.setEnabled(false);
            cboVinos.setEnabled(true);}
    }//GEN-LAST:event_rbtnVinosActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Lógica para agregar un plato
        if (txtNombre.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el nombre de la bebida.");
            txtNombre.requestFocus();
            return;
        }

        if (txtDescripcion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar la descripción.");
            txtDescripcion.requestFocus();
            return;
        }

        if (txtObservaciones.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar la observación.");
            txtObservaciones.requestFocus();
            return;
        }

        if (txtPrecio.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el precio de la bebida.");
            txtPrecio.requestFocus();
            return;
        }

        if (txtEstado.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el estado.");
            txtEstado.requestFocus();
            return;
        }
        Comidas dts = new Comidas();
    // Instanciar la clase FunComidas para operaciones lógicas
        FunComidas func = new FunComidas();
    
    // Crear objeto Comidas con los datos del formulario
        dts.setNombre(txtNombre.getText());
        dts.setDescripcion(txtDescripcion.getText());
        dts.setObservacion(txtObservaciones.getText());
        dts.setValor(Double.parseDouble(txtPrecio.getText()));
        dts.setStock(Integer.parseInt(txtStock.getText()));
        dts.setEstado(txtEstado.getText());
    
    // Insertar la comida usando la función de la clase FunComidas
    if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "Bebida agregada correctamente.");
                mostrar("");  // Método para actualizar la tabla de comidas
                inhabilitar();
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Error al agregar la bebida.");
            }
        } else if (accion.equals("editar")) {
            dts.setIdplato(Integer.parseInt(txtidplato.getText()));
            if (func.editar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "El registro de la bebida fue editado correctamente.");
                mostrar("");  // Método para actualizar la tabla de comidas
                inhabilitar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al editar la bebida.");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // Lógica para eliminar un plato
         if (!txtidplato.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de eliminar?", "Confirmar", 2);

            if (confirmacion == 0) {
                FunComidas func = new FunComidas();
                Comidas dts = new Comidas();

                dts.setIdplato(Integer.parseInt(txtidplato.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        inhabilitar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblBebidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBebidasMouseClicked
        // TODO add your handling code here:
        // Lógica para cargar los datos en los campos al hacer clic en una fila
        btnGuardar.setText("Editar");
        habilitar();
        btnEliminar.setEnabled(true);
        
        accion = "editar";
        int fila = tblBebidas.rowAtPoint(evt.getPoint());
        txtidplato.setText(tblBebidas.getValueAt(fila, 0).toString());
        txtNombre.setText(tblBebidas.getValueAt(fila, 1).toString());
        txtDescripcion.setText(tblBebidas.getValueAt(fila, 2).toString());
        txtObservaciones.setText(tblBebidas.getValueAt(fila, 3).toString());
        txtPrecio.setText(tblBebidas.getValueAt(fila, 4).toString());
        txtStock.setText(tblBebidas.getValueAt(fila, 5).toString());
        txtEstado.setText(tblBebidas.getValueAt(fila, 6).toString());
    }//GEN-LAST:event_tblBebidasMouseClicked

    private void brnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnGuardar.setText("GUARDAR");
        accion = "guardar";
    }//GEN-LAST:event_brnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void mostrarMensaje(String mensaje) {
    JOptionPane.showMessageDialog(this, mensaje);
    }
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComidasUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnNuevo;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cboAguas;
    private javax.swing.JComboBox<String> cboCervezas;
    private javax.swing.JComboBox<String> cboJugos;
    private javax.swing.JComboBox<String> cboRefrescos;
    private javax.swing.JComboBox<String> cboVinos;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelP;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlabel2;
    private javax.swing.JLabel lblTotalBebidas;
    private javax.swing.JRadioButton rbtnAguas;
    private javax.swing.JRadioButton rbtnCervezas;
    private javax.swing.JRadioButton rbtnJugos;
    private javax.swing.JRadioButton rbtnRefrescos;
    private javax.swing.JRadioButton rbtnVinos;
    private javax.swing.JTable tblBebidas;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtidplato;
    // End of variables declaration//GEN-END:variables
}
