/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FunComidas;
import datos.Comidas;
import javax.swing.ButtonGroup;

/**
 *
 * @author USER1
 */
public class ComidasUI extends javax.swing.JInternalFrame {
    private String accion = "guardar";
    private final ButtonGroup grupoComidas; // ButtonGroup para agrupar los radio buttons
    private final FunComidas funComidas; // Declaración de la variable
    private final DefaultTableModel modeloTabla; // Modelo de tabla para platos

    /**
     * Creates new form ComidasUI
     */
    public ComidasUI() {
        initComponents();
        inhabilitar();

        
        grupoComidas = new ButtonGroup(); // Inicializar el ButtonGroup
        funComidas = new FunComidas(); // Puedes ajustar la inicialización según tus necesidades
        
        // Agregar los radio buttons al ButtonGroup
        grupoComidas.add(rbtnHamburguesa);
        grupoComidas.add(rbtnPizza);
        grupoComidas.add(rbtnHotDog);
        grupoComidas.add(rbtnSandwich);
        grupoComidas.add(rbtnPFritas);
        
        modeloTabla = (DefaultTableModel) tblPlatos.getModel();
        modeloTabla.addColumn("idplato");
        modeloTabla.addColumn("nombre");
        modeloTabla.addColumn("descripcion");
        modeloTabla.addColumn("observacion");
        modeloTabla.addColumn("valor");
        modeloTabla.addColumn("stock");
        modeloTabla.addColumn("estado");  
        mostrar("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPlatos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanelGComidas = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelDescripcion = new javax.swing.JLabel();
        jLabelPrecio = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtObservaciones = new javax.swing.JTextField();
        jlabel = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelComidaRapidas = new javax.swing.JLabel();
        jPanelCRapidas = new javax.swing.JPanel();
        rbtnHamburguesa = new javax.swing.JRadioButton();
        rbtnPizza = new javax.swing.JRadioButton();
        rbtnHotDog = new javax.swing.JRadioButton();
        rbtnSandwich = new javax.swing.JRadioButton();
        rbtnPFritas = new javax.swing.JRadioButton();
        cbxHamburguesa = new javax.swing.JComboBox<>();
        cbxPizza = new javax.swing.JComboBox<>();
        cbxHotDog = new javax.swing.JComboBox<>();
        cbxSandwich = new javax.swing.JComboBox<>();
        cbxPFritas = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtidplato = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPlatos = new javax.swing.JTable();
        lblOSeleccionada = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setTitle("COMIDAS RAPIDAS - PLATOS");

        jLabelPlatos.setFont(new java.awt.Font("Sitka Text", 3, 36)); // NOI18N
        jLabelPlatos.setForeground(new java.awt.Color(51, 102, 255));
        jLabelPlatos.setText("Platos");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabelNombre.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabelNombre.setForeground(new java.awt.Color(51, 51, 51));
        jLabelNombre.setText("Nombre:");

        jLabelDescripcion.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabelDescripcion.setForeground(new java.awt.Color(51, 51, 51));
        jLabelDescripcion.setText("Descripción:");

        jLabelPrecio.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabelPrecio.setForeground(new java.awt.Color(51, 51, 51));
        jLabelPrecio.setText("Precio:");

        txtNombre.setBackground(new java.awt.Color(204, 204, 204));

        txtDescripcion.setBackground(new java.awt.Color(204, 204, 204));

        txtPrecio.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Observación:");

        txtObservaciones.setBackground(new java.awt.Color(204, 204, 204));

        jlabel.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jlabel.setForeground(new java.awt.Color(51, 51, 51));
        jlabel.setText("Estado:");

        txtEstado.setBackground(new java.awt.Color(204, 204, 204));

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Stock:");

        txtStock.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanelGComidasLayout = new javax.swing.GroupLayout(jPanelGComidas);
        jPanelGComidas.setLayout(jPanelGComidasLayout);
        jPanelGComidasLayout.setHorizontalGroup(
            jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGComidasLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGComidasLayout.createSequentialGroup()
                        .addComponent(jLabelPrecio)
                        .addGap(43, 43, 43)
                        .addComponent(txtPrecio))
                    .addGroup(jPanelGComidasLayout.createSequentialGroup()
                        .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescripcion)
                            .addComponent(jLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGComidasLayout.createSequentialGroup()
                                .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(1, 1, 1))
                            .addComponent(txtDescripcion)))
                    .addGroup(jPanelGComidasLayout.createSequentialGroup()
                        .addComponent(jlabel)
                        .addGap(41, 41, 41)
                        .addComponent(txtEstado))
                    .addGroup(jPanelGComidasLayout.createSequentialGroup()
                        .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtObservaciones)
                            .addComponent(txtStock))))
                .addContainerGap())
        );
        jPanelGComidasLayout.setVerticalGroup(
            jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGComidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescripcion)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtObservaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelGComidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabel)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jLabelComidaRapidas.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabelComidaRapidas.setForeground(new java.awt.Color(255, 153, 153));
        jLabelComidaRapidas.setText("Comidas Rápidas");

        rbtnHamburguesa.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnHamburguesa.setForeground(new java.awt.Color(51, 51, 51));
        rbtnHamburguesa.setText("Hamburguesa");
        rbtnHamburguesa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnHamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHamburguesaActionPerformed(evt);
            }
        });

        rbtnPizza.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnPizza.setForeground(new java.awt.Color(51, 51, 51));
        rbtnPizza.setText("Pizza");
        rbtnPizza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPizzaActionPerformed(evt);
            }
        });

        rbtnHotDog.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnHotDog.setForeground(new java.awt.Color(51, 51, 51));
        rbtnHotDog.setText("Hot Dog");
        rbtnHotDog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnHotDog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnHotDogActionPerformed(evt);
            }
        });

        rbtnSandwich.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnSandwich.setForeground(new java.awt.Color(51, 51, 51));
        rbtnSandwich.setText("Sándwich");
        rbtnSandwich.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnSandwich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSandwichActionPerformed(evt);
            }
        });

        rbtnPFritas.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        rbtnPFritas.setForeground(new java.awt.Color(51, 51, 51));
        rbtnPFritas.setText("Papas Fritas");
        rbtnPFritas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        rbtnPFritas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPFritasActionPerformed(evt);
            }
        });

        cbxHamburguesa.setBackground(new java.awt.Color(204, 255, 255));
        cbxHamburguesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasica", "Pollo", "Vegana", "Mexicana", "Sencilla" }));

        cbxPizza.setBackground(new java.awt.Color(204, 255, 255));
        cbxPizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 Estaciones", "Queso", "Super 4 Estaciones", "Tropical", "Hawaiana", "Exotica", "Americana", "Milano", "Vegetariana", "Tejana", "Continental", "Oriental" }));

        cbxHotDog.setBackground(new java.awt.Color(204, 255, 255));
        cbxHotDog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Clasico", "Sonora", "Mexicana", "gourmet" }));

        cbxSandwich.setBackground(new java.awt.Color(204, 255, 255));
        cbxSandwich.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mixto", "Cubano", "Pollo", "Atún", "Aguacate", "Jamón" }));

        cbxPFritas.setBackground(new java.awt.Color(204, 255, 255));
        cbxPFritas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pollo", "Chorizo" }));

        javax.swing.GroupLayout jPanelCRapidasLayout = new javax.swing.GroupLayout(jPanelCRapidas);
        jPanelCRapidas.setLayout(jPanelCRapidasLayout);
        jPanelCRapidasLayout.setHorizontalGroup(
            jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCRapidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCRapidasLayout.createSequentialGroup()
                        .addComponent(rbtnHamburguesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCRapidasLayout.createSequentialGroup()
                        .addComponent(rbtnPFritas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbxPFritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCRapidasLayout.createSequentialGroup()
                        .addComponent(rbtnPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelCRapidasLayout.createSequentialGroup()
                        .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(rbtnHotDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rbtnSandwich, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxSandwich, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxHotDog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanelCRapidasLayout.setVerticalGroup(
            jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCRapidasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnHamburguesa)
                    .addComponent(cbxHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPizza)
                    .addComponent(cbxPizza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnHotDog)
                    .addComponent(cbxHotDog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnSandwich)
                    .addComponent(cbxSandwich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCRapidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnPFritas)
                    .addComponent(cbxPFritas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 153));
        jLabel8.setText("Gestión Comidas");

        btnGuardar.setIcon(new javax.swing.ImageIcon("D:\\2 semestre\\NetBeansProjects\\GestionAcademico\\src\\main\\java\\SistemaAcademico\\file\\salvar.png")); // NOI18N
        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setIcon(new javax.swing.ImageIcon("D:\\2 semestre\\NetBeansProjects\\GestionAcademico\\src\\main\\java\\SistemaAcademico\\file\\Limpiar.png")); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel4.setText("INGRESO PEDIDOS");

        btnNuevo.setIcon(new javax.swing.ImageIcon("D:\\2 semestre\\NetBeansProjects\\GestionAcademico\\src\\main\\java\\SistemaAcademico\\file\\nueva-cuenta.png")); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidplato, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnNuevo)
                        .addGap(41, 41, 41)
                        .addComponent(btnGuardar)
                        .addGap(39, 39, 39)
                        .addComponent(btnLimpiar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabelComidaRapidas)
                                .addGap(95, 95, 95)
                                .addComponent(jLabel8))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanelCRapidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanelGComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComidaRapidas)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtidplato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanelCRapidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelGComidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLimpiar)
                            .addComponent(btnGuardar)
                            .addComponent(btnNuevo))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        tblPlatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPlatosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPlatos);

        lblOSeleccionada.setText("Opción Seleccionada");

        jLabel2.setText("INGRESO DE LA COMIDA");

        btnEliminar.setIcon(new javax.swing.ImageIcon("D:\\2 semestre\\NetBeansProjects\\GestionAcademico\\src\\main\\java\\SistemaAcademico\\file\\usuario.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon("D:\\2 semestre\\NetBeansProjects\\GestionAcademico\\src\\main\\java\\SistemaAcademico\\file\\cerrar-sesion.png")); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOSeleccionada)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnSalir))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(lblOSeleccionada))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(491, 491, 491)
                .addComponent(jLabelPlatos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPlatos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    void mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            FunComidas func = new FunComidas();
            modelo = func.mostrar(buscar);

            tblPlatos.setModel(modelo);
            lblOSeleccionada.setText("Total Registros " + Integer.toString(func.totalRegistros));
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, e);
        }
    }
    //Metodo para ocultar las columnas de la tabla
    void ocultarColumnas() {
        tblPlatos.getColumnModel().getColumn(0).setMaxWidth(0);
        tblPlatos.getColumnModel().getColumn(0).setMinWidth(0);
        tblPlatos.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    void inhabilitar() {
        txtidplato.setVisible(false);
        txtNombre.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtObservaciones.setEnabled(false);
        txtPrecio.setEnabled(false);
        txtStock.setEnabled(false);
        txtEstado.setEnabled(false);
        
        btnGuardar.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnLimpiar.setEnabled(false);
    
        txtidplato.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtObservaciones.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtEstado.setText("");
    
    }
    void habilitar() {
        txtidplato.setVisible(false);
        txtNombre.setEnabled(true);
        txtDescripcion.setEnabled(true);
        txtObservaciones.setEnabled(true);
        txtPrecio.setEnabled(true);
        txtStock.setEnabled(true);
        txtEstado.setEnabled(true);
        
        btnGuardar.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnLimpiar.setEnabled(true);
    
        txtidplato.setText("");
        txtNombre.setText("");
        txtDescripcion.setText("");
        txtObservaciones.setText("");
        txtPrecio.setText("");
        txtStock.setText("");
        txtEstado.setText("");
    } 

    private void rbtnHamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHamburguesaActionPerformed
        // TODO add your handling code here:
        //lógica cuando se selecciona la opción Hamburgesa
        if (rbtnHamburguesa.isSelected()) {
            mostrarMensaje("Hamburguesa seleccionada");
            cbxHamburguesa.setEnabled(true);
            cbxPizza.setEnabled(false);
            cbxHotDog.setEnabled(false);
            cbxSandwich.setEnabled(false);
            cbxPFritas.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnHamburguesaActionPerformed

    private void rbtnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPizzaActionPerformed
        // TODO add your handling code here:
        //lógica cuando se selecciona la opción Pizza
        if (rbtnPizza.isSelected()) {
            mostrarMensaje("Pizza seleccionada");
            cbxHamburguesa.setEnabled(false);
            cbxPizza.setEnabled(true);
            cbxHotDog.setEnabled(false);
            cbxSandwich.setEnabled(false);
            cbxPFritas.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnPizzaActionPerformed

    private void rbtnHotDogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnHotDogActionPerformed
        // TODO add your handling code here:
        //lógica cuando se selecciona la opción Hot Dog
        if (rbtnHotDog.isSelected()) {
            mostrarMensaje("Hot Dog seleccionado");
            cbxHamburguesa.setEnabled(false);
            cbxPizza.setEnabled(false);
            cbxHotDog.setEnabled(true);
            cbxSandwich.setEnabled(false);
            cbxPFritas.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnHotDogActionPerformed

    private void rbtnSandwichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSandwichActionPerformed
        // TODO add your handling code here:
        if (rbtnSandwich.isSelected()) {
            mostrarMensaje("Sandwich seleccionado");
            cbxHamburguesa.setEnabled(false);
            cbxPizza.setEnabled(false);
            cbxHotDog.setEnabled(false);
            cbxSandwich.setEnabled(true);
            cbxPFritas.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnSandwichActionPerformed

    private void rbtnPFritasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPFritasActionPerformed
        // TODO add your handling code here:
        //la lógica cuando se selecciona la opción Papas Fritas
        if (rbtnPFritas.isSelected()) {
            mostrarMensaje("Papas Fritas seleccionadas");
            cbxHamburguesa.setEnabled(false);
            cbxPizza.setEnabled(false);
            cbxHotDog.setEnabled(false);
            cbxSandwich.setEnabled(false);
            cbxPFritas.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnPFritasActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        // Lógica para agregar un plato
        if (txtNombre.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el nombre de la comida.");
            txtNombre.requestFocus();
            return;
        }

        if (txtDescripcion.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar la descripción de la comida.");
            txtDescripcion.requestFocus();
            return;
        }

        if (txtObservaciones.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar la observación.");
            txtObservaciones.requestFocus();
            return;
        }

        if (txtPrecio.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el precio de la comida.");
            txtPrecio.requestFocus();
            return;
        }

        if (txtEstado.getText().length() == 0) {
            JOptionPane.showConfirmDialog(rootPane, "Debe ingresar el estado de la comida.");
            txtEstado.requestFocus();
            return;
        }
        Comidas dts = new Comidas();
    // Instanciar la clase FunComidas para operaciones lógicas
        FunComidas func = new FunComidas();
    
    // Crear objeto Comidas con los datos del formulario
        dts.setNombre(txtNombre.getText());
        dts.setDescripcion(txtDescripcion.getText());
        dts.setObservacion(txtObservaciones.getText());
        dts.setValor(Double.parseDouble(txtPrecio.getText()));
        dts.setStock(Integer.parseInt(txtStock.getText()));
        dts.setEstado(txtEstado.getText());
    
    // Insertar la comida usando la función de la clase FunComidas
    if (accion.equals("guardar")) {
            if (func.insertar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "Comida agregada correctamente.");
                mostrar("");  // Método para actualizar la tabla de comidas
                inhabilitar();
            } else {
                JOptionPane.showConfirmDialog(rootPane, "Error al agregar la comida.");
            }
        } else if (accion.equals("editar")) {
            dts.setIdplato(Integer.parseInt(txtidplato.getText()));
            if (func.editar(dts)) {
                JOptionPane.showConfirmDialog(rootPane, "El registro de la comida fue editado correctamente.");
                mostrar("");  // Método para actualizar la tabla de comidas
                inhabilitar();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Error al editar la comida.");
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        // Lógica para eliminar un plato
         if (!txtidplato.getText().equals("")) {
            int confirmacion = JOptionPane.showConfirmDialog(rootPane, "Estás seguro de eliminar el plato?", "Confirmar", 2);

            if (confirmacion == 0) {
                FunComidas func = new FunComidas();
                Comidas dts = new Comidas();

                dts.setIdplato(Integer.parseInt(txtidplato.getText()));
                func.eliminar(dts);
                mostrar("");
                inhabilitar();
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        inhabilitar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void tblPlatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPlatosMouseClicked
        // TODO add your handling code here:
        // Lógica para cargar los datos en los campos al hacer clic en una fila
        btnGuardar.setText("Editar");
        habilitar();
        btnEliminar.setEnabled(true);
        
        accion = "editar";
        int fila = tblPlatos.rowAtPoint(evt.getPoint());
        txtidplato.setText(tblPlatos.getValueAt(fila, 0).toString());
        txtNombre.setText(tblPlatos.getValueAt(fila, 1).toString());
        txtDescripcion.setText(tblPlatos.getValueAt(fila, 2).toString());
        txtObservaciones.setText(tblPlatos.getValueAt(fila, 3).toString());
        txtPrecio.setText(tblPlatos.getValueAt(fila, 4).toString());
        txtStock.setText(tblPlatos.getValueAt(fila, 5).toString());
        txtEstado.setText(tblPlatos.getValueAt(fila, 6).toString());

    }//GEN-LAST:event_tblPlatosMouseClicked

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        habilitar();
        btnGuardar.setText("GUARDAR");
        accion = "guardar"; 
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed
  
    private void mostrarMensaje(String mensaje) {
    JOptionPane.showMessageDialog(this, mensaje);
    }
    public static void main(String args[]) {
        
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComidasUI().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cbxHamburguesa;
    private javax.swing.JComboBox<String> cbxHotDog;
    private javax.swing.JComboBox<String> cbxPFritas;
    private javax.swing.JComboBox<String> cbxPizza;
    private javax.swing.JComboBox<String> cbxSandwich;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelComidaRapidas;
    private javax.swing.JLabel jLabelDescripcion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPlatos;
    private javax.swing.JLabel jLabelPrecio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelCRapidas;
    private javax.swing.JPanel jPanelGComidas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel lblOSeleccionada;
    private javax.swing.JRadioButton rbtnHamburguesa;
    private javax.swing.JRadioButton rbtnHotDog;
    private javax.swing.JRadioButton rbtnPFritas;
    private javax.swing.JRadioButton rbtnPizza;
    private javax.swing.JRadioButton rbtnSandwich;
    private javax.swing.JTable tblPlatos;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtObservaciones;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtidplato;
    // End of variables declaration//GEN-END:variables

    private static class funComidas {

        private static boolean insertar(Comidas comida) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public funComidas() {
        }
    }
}
