package presentacion;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

public class MenuPrincipalUI extends javax.swing.JFrame {

    private LoginUI login;
    private MesasUI mesas;
    private UsuarioUI usuario;
    private ComidasUI comidas;
    private BebidasUI bebidas;
    private PedidosUI pedidos;

    public MenuPrincipalUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuLogin = new javax.swing.JMenu();
        mnuIngresar = new javax.swing.JMenuItem();
        mnuCerrarSesion = new javax.swing.JMenuItem();
        mnuSalir = new javax.swing.JMenuItem();
        mnuUsuarios = new javax.swing.JMenu();
        mnuAdminUser = new javax.swing.JMenuItem();
        mnuPlatos = new javax.swing.JMenu();
        mnuComida = new javax.swing.JMenuItem();
        mnuBebidas = new javax.swing.JMenuItem();
        mnuPedidos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnuMesas = new javax.swing.JMenu();
        mnuAdminMesas = new javax.swing.JMenuItem();
        mnuFacturacion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Comida Rápida");

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 518, Short.MAX_VALUE)
        );

        mnuLogin.setText("Login");

        mnuIngresar.setText("Ingresar");
        mnuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuIngresarActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuIngresar);

        mnuCerrarSesion.setText("Cerrar Sesión");
        mnuCerrarSesion.setEnabled(false);
        mnuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCerrarSesionActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuCerrarSesion);

        mnuSalir.setText("Salir");
        mnuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalirActionPerformed(evt);
            }
        });
        mnuLogin.add(mnuSalir);

        jMenuBar1.add(mnuLogin);

        mnuUsuarios.setText("Usuarios");
        mnuUsuarios.setEnabled(false);

        mnuAdminUser.setText("Administrar");
        mnuAdminUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminUserActionPerformed(evt);
            }
        });
        mnuUsuarios.add(mnuAdminUser);

        jMenuBar1.add(mnuUsuarios);

        mnuPlatos.setText("Platos");
        mnuPlatos.setEnabled(false);

        mnuComida.setText("Comidas");
        mnuComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuComidaActionPerformed(evt);
            }
        });
        mnuPlatos.add(mnuComida);

        mnuBebidas.setText("Bebidas");
        mnuBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBebidasActionPerformed(evt);
            }
        });
        mnuPlatos.add(mnuBebidas);

        jMenuBar1.add(mnuPlatos);

        mnuPedidos.setText("Pedidos");
        mnuPedidos.setEnabled(false);
        mnuPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPedidosActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Ver Pedidos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuPedidos.add(jMenuItem1);

        jMenuBar1.add(mnuPedidos);

        mnuMesas.setText("Mesas");
        mnuMesas.setEnabled(false);

        mnuAdminMesas.setText("Administrar");
        mnuAdminMesas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAdminMesasActionPerformed(evt);
            }
        });
        mnuMesas.add(mnuAdminMesas);

        jMenuBar1.add(mnuMesas);

        mnuFacturacion.setText("Facturación");
        mnuFacturacion.setEnabled(false);
        jMenuBar1.add(mnuFacturacion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuIngresarActionPerformed
        // TODO add your handling code here:
        if (login == null || login.isClosed()) {
            login = new LoginUI(MenuPrincipalUI.this);
            escritorio.add(login);
            login.setVisible(true);
        } else {
            try {
                login.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnuIngresarActionPerformed

    private void mnuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_mnuSalirActionPerformed

    private void mnuAdminUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminUserActionPerformed
        // TODO add your handling code here:
        if (usuario == null || usuario.isClosed()) {
            usuario = new UsuarioUI(escritorio);
            escritorio.add(usuario);
            usuario.setVisible(true);
        } else {
            try {
                usuario.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnuAdminUserActionPerformed

    private void mnuAdminMesasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAdminMesasActionPerformed
        // TODO add your handling code here:
        if (mesas == null || mesas.isClosed()) {
            mesas = new MesasUI();
            escritorio.add(mesas);
            mesas.setVisible(true);
        } else {
            try {
                mesas.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_mnuAdminMesasActionPerformed

    private void mnuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCerrarSesionActionPerformed
        // TODO add your handling code here:
        JInternalFrame[] allFrames = escritorio.getAllFrames();
        for (JInternalFrame frame : allFrames) {
            frame.dispose();
        }
        mnuIngresar.setEnabled(true);
        mnuCerrarSesion.setEnabled(false);
        mnuUsuarios.setEnabled(false);
        mnuPlatos.setEnabled(false);
        mnuPedidos.setEnabled(false);
        mnuMesas.setEnabled(false);
        mnuFacturacion.setEnabled(false);

        JOptionPane.showMessageDialog(this, "Usuario se desconectó correctamente.");
    }//GEN-LAST:event_mnuCerrarSesionActionPerformed

    private void mnuComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuComidaActionPerformed
        // TODO add your handling code here:
        // Acción para mostrar el JInternalFrame de Comidas
        if (comidas == null || comidas.isClosed()) {
            comidas = new ComidasUI();
            escritorio.add(comidas);
        }
        comidas.setVisible(true);

        try {
            comidas.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mnuComidaActionPerformed

    private void mnuBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBebidasActionPerformed
        // TODO add your handling code here:
        // Acción para mostrar el JInternalFrame de Bebidas
        if (bebidas == null || bebidas.isClosed()) {
            bebidas = new BebidasUI();
            escritorio.add(bebidas);
        }
        bebidas.setVisible(true);
        try {
            bebidas.setSelected(true);
        } catch (java.beans.PropertyVetoException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_mnuBebidasActionPerformed

    private void mnuPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPedidosActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuPedidosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if (pedidos == null || pedidos.isClosed()) {
            pedidos = new PedidosUI();
            escritorio.add(pedidos);
            pedidos.setVisible(true);
        } else {
            try {
                pedidos.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipalUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipalUI().setVisible(true);
            }
        });
    }

    public void habilitarMenuIngresar(boolean habilitar) {
        mnuIngresar.setEnabled(habilitar);
    }

    public void habilitarMenuCerrarSesion(boolean habilitar) {
        mnuCerrarSesion.setEnabled(habilitar);
    }

    public void habilitarMenuUsuario(boolean habilitar) {
        mnuUsuarios.setEnabled(habilitar);
    }

    public void habilitarMenuPlatos(boolean habilitar) {
        mnuPlatos.setEnabled(habilitar);
    }

    public void habilitarMenuPedidos(boolean habilitar) {
        mnuPedidos.setEnabled(habilitar);
    }

    public void habilitarMenuMesas(boolean habilitar) {
        mnuMesas.setEnabled(habilitar);
    }

    public void habilitarMenuFacturacion(boolean habilitar) {
        mnuFacturacion.setEnabled(habilitar);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem mnuAdminMesas;
    private javax.swing.JMenuItem mnuAdminUser;
    private javax.swing.JMenuItem mnuBebidas;
    private javax.swing.JMenuItem mnuCerrarSesion;
    private javax.swing.JMenuItem mnuComida;
    private javax.swing.JMenu mnuFacturacion;
    private javax.swing.JMenuItem mnuIngresar;
    private javax.swing.JMenu mnuLogin;
    private javax.swing.JMenu mnuMesas;
    private javax.swing.JMenu mnuPedidos;
    private javax.swing.JMenu mnuPlatos;
    private javax.swing.JMenuItem mnuSalir;
    private javax.swing.JMenu mnuUsuarios;
    // End of variables declaration//GEN-END:variables
}
