/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;


import datos.MesasDatos;
import logica.FunMesas;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author German
 */
public class Mesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mesas
     */
    private DefaultTableModel modeloMesas;
    private FunMesas funMesas;

    public Mesas() {

        initComponents();
        funMesas = new FunMesas();
        initTable();
        setTitle("Mesas");
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    private void initTable() {
        modeloMesas = funMesas.mostrar();
        tblMesas.setModel(modeloMesas);
        

        //ACTUALIZACION IMPORTANTE
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID MESA", "CAPACIDAD", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblMesas);

        btnAgregar.setBackground(new java.awt.Color(51, 51, 255));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setIcon(new javax.swing.ImageIcon("C:\\Users\\princ\\OneDrive\\Documentos\\GitHub\\comida_rapida\\ComidaRapida\\src\\main\\java\\files\\imgAgregar..png")); // NOI18N
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignar.setIcon(new javax.swing.ImageIcon("C:\\Users\\princ\\OneDrive\\Documentos\\GitHub\\comida_rapida\\ComidaRapida\\src\\main\\java\\files\\imgAsignar...png")); // NOI18N
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setIcon(new javax.swing.ImageIcon("C:\\Users\\princ\\OneDrive\\Documentos\\GitHub\\comida_rapida\\ComidaRapida\\src\\main\\java\\files\\imgEditar.png")); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\princ\\OneDrive\\Documentos\\GitHub\\comida_rapida\\ComidaRapida\\src\\main\\java\\files\\ingEliminar.png")); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLiberar.setForeground(new java.awt.Color(255, 255, 255));
        btnLiberar.setIcon(new javax.swing.ImageIcon("C:\\Users\\princ\\OneDrive\\Documentos\\GitHub\\comida_rapida\\ComidaRapida\\src\\main\\java\\files\\imgLiberar.png")); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAsignar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLiberar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        
    String capacidad = JOptionPane.showInputDialog(this, "Ingrese la capacidad de la mesa:");
    if (capacidad != null && !capacidad.isEmpty()) {
        MesasDatos nuevaMesa = new MesasDatos(0, Integer.parseInt(capacidad), "Disponible");
        funMesas.insertarMesa(nuevaMesa);
        modeloMesas = funMesas.mostrar();
        tblMesas.setModel(modeloMesas);
    }
   
     
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
    if (selectedRow != -1) {
        int id = Integer.parseInt(modeloMesas.getValueAt(selectedRow, 0).toString());
        funMesas.actualizarEstadoMesa(id, "Ocupada");
        modeloMesas = funMesas.mostrar();
        tblMesas.setModel(modeloMesas);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa para asignar.");
    }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
    if (selectedRow != -1) {
        String capacidad = JOptionPane.showInputDialog(this, "Ingrese la nueva capacidad de la mesa:");
        if (capacidad != null && !capacidad.isEmpty()) {
            int id = Integer.parseInt(modeloMesas.getValueAt(selectedRow, 0).toString());
            funMesas.actualizarCapacidadMesa(id, Integer.parseInt(capacidad));
            modeloMesas = funMesas.mostrar();
            tblMesas.setModel(modeloMesas);
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa para editar.");
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
    if (selectedRow != -1) {
        int id = Integer.parseInt(modeloMesas.getValueAt(selectedRow, 0).toString());
        funMesas.eliminarMesa(id);
        modeloMesas = funMesas.mostrar();
        tblMesas.setModel(modeloMesas);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa para eliminar.");
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
    if (selectedRow != -1) {
        int id = Integer.parseInt(modeloMesas.getValueAt(selectedRow, 0).toString());
        funMesas.actualizarEstadoMesa(id, "Disponible");
        modeloMesas = funMesas.mostrar();
        tblMesas.setModel(modeloMesas);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una mesa para liberar.");
    }
    }//GEN-LAST:event_btnLiberarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMesas;
    // End of variables declaration//GEN-END:variables
}
