/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package presentacion;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author princ
 */
public class Mesas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mesas
     */
    private DefaultTableModel modeloMesas;
    
    public Mesas() {
        
        initComponents();
        initTable();
        setTitle("Mesas");
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    private void initTable() {
        modeloMesas = new DefaultTableModel();
        modeloMesas.addColumn("ID MESA");
        modeloMesas.addColumn("Capacidad");
        modeloMesas.addColumn("Estado");

        // Aquí puedes agregar datos de ejemplo o cargar desde la base de datos
        modeloMesas.addRow(new Object[]{1, 4, "Disponible"});
        modeloMesas.addRow(new Object[]{2, 2, "Ocupada"});

        tblMesas.setModel(modeloMesas);
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID MESA", "CAPACIDAD", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(tblMesas);

        btnAgregar.setBackground(new java.awt.Color(51, 51, 255));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnAsignar.setBackground(new java.awt.Color(51, 51, 255));
        btnAsignar.setForeground(new java.awt.Color(255, 255, 255));
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(51, 51, 255));
        btnEditar.setForeground(new java.awt.Color(255, 255, 255));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(51, 51, 255));
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLiberar.setBackground(new java.awt.Color(51, 51, 255));
        btnLiberar.setForeground(new java.awt.Color(255, 255, 255));
        btnLiberar.setText("Liberar");
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnAgregar)
                        .addGap(70, 70, 70)
                        .addComponent(btnAsignar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLiberar)
                        .addGap(109, 109, 109))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnAsignar)
                    .addComponent(btnEditar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLiberar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
            // TODO add your handling code here:
            String capacidad = JOptionPane.showInputDialog(this, "Ingrese la capacidad de la mesa:");
        if (capacidad != null && !capacidad.isEmpty()) {
            int id = modeloMesas.getRowCount() + 1;
            modeloMesas.addRow(new Object[]{id, Integer.parseInt(capacidad), "Disponible"});
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
        if (selectedRow != -1) {
            modeloMesas.setValueAt("Ocupada", selectedRow, 2);
            // Aquí puedes agregar código adicional para asociar el pedido a la mesa en la base de datos
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para asignar.");
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
        if (selectedRow != -1) {
            String capacidad = JOptionPane.showInputDialog(this, "Ingrese la nueva capacidad de la mesa:");
            if (capacidad != null && !capacidad.isEmpty()) {
                modeloMesas.setValueAt(Integer.parseInt(capacidad), selectedRow, 1);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para editar.");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
        if (selectedRow != -1) {
            modeloMesas.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para eliminar.");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblMesas.getSelectedRow();
        if (selectedRow != -1) {
            modeloMesas.setValueAt("Disponible", selectedRow, 2);
            // Aquí puedes agregar código adicional para desasociar el pedido de la mesa en la base de datos
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione una mesa para liberar.");
        }
    }//GEN-LAST:event_btnLiberarActionPerformed
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMesas;
    // End of variables declaration//GEN-END:variables
}
