package presentacion;

import datos.Rol;
import datos.Usuario;
import datos.UsuarioRol;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.FunRol;
import logica.FunUsuarioRol;
import utils.HelpTabla;

public class RolUI extends javax.swing.JInternalFrame {

    private Usuario usuario;
    private FunRol funrol = new FunRol();
    private DefaultComboBoxModel valores_combo = new DefaultComboBoxModel();
    private UsuarioUI usuarioui;

    public RolUI(UsuarioUI usuarioui) {
        initComponents();
        this.usuarioui = usuarioui;
        this.usuario = this.usuarioui.getUsuario();
        txtIdUsuario.setText(String.valueOf(this.usuario.getId_usuario()));
        txtLogin.setText(this.usuario.getLogin());
        mostrarDatos(this.usuario);
        cargar_combo();
        HelpTabla.ajustarAnchoColumnas(tableRol);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnQuitar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        txtIdUsuario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableRol = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbRol = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Roles de Usuario");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnQuitar.setText("Quitar");
        btnQuitar.setEnabled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnAsignar.setText("Asignar");
        btnAsignar.setEnabled(false);
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        txtIdUsuario.setEnabled(false);

        jLabel7.setText("Login:");

        txtLogin.setEnabled(false);

        jLabel9.setText("ID Usuario:");

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        tableRol = new javax.swing.JTable(){
            public boolean isCellEditable(int row, int column){
                return false;
            }
        };
        tableRol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableRol.setAutoResizeMode(0);
        tableRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableRolMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableRol);

        jLabel1.setText("Rol:");

        cmbRol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbRolItemStateChanged(evt);
            }
        });

        jLabel2.setText("Roles Asignados");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(cmbRol, 0, 221, Short.MAX_VALUE)
                                .addComponent(txtLogin)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtIdUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnQuitar)
                    .addComponent(btnAsignar))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        if (cmbRol.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el rol.");
            cmbRol.requestFocus();
            return;
        }

        FunUsuarioRol func = new FunUsuarioRol();
        UsuarioRol dts = new UsuarioRol();

        Rol rol = (Rol) cmbRol.getSelectedItem();
        dts.setUsuario(usuario);
        dts.setRol(rol);

        if (func.eliminar(dts)) {
            JOptionPane.showMessageDialog(this, "Rol eliminado correctamente.");
            mostrarDatos(usuario);
            HelpTabla.ajustarAnchoColumnas(tableRol);
            cmbRol.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        // TODO add your handling code here:
        if (cmbRol.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar el rol.");
            cmbRol.requestFocus();
            return;
        }

        FunUsuarioRol func = new FunUsuarioRol();
        UsuarioRol dts = new UsuarioRol();

        Rol rol = (Rol) cmbRol.getSelectedItem();
        dts.setUsuario(usuario);
        dts.setRol(rol);

        if (func.insertar(dts)) {
            JOptionPane.showMessageDialog(this, "Rol registrado correctamente.");
            mostrarDatos(usuario);
            HelpTabla.ajustarAnchoColumnas(tableRol);
            cmbRol.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        usuarioui.mostrarPantalla();
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void tableRolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableRolMouseClicked
        // TODO add your handling code here:
        int fila = tableRol.getSelectedRow();
        for (int i = 0; i < cmbRol.getItemCount(); i++) {
            Rol rol = cmbRol.getItemAt(i);
            if (rol.getId_rol() == Integer.parseInt(tableRol.getValueAt(fila, 0).toString())) {
                cmbRol.setSelectedIndex(i);
                break;
            }
        }
        btnAsignar.setEnabled(false);
        btnQuitar.setEnabled(true);
    }//GEN-LAST:event_tableRolMouseClicked

    private void cmbRolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbRolItemStateChanged
        // TODO add your handling code here:
        Rol rol;
        if (cmbRol.getSelectedIndex() == 0) {
            btnAsignar.setEnabled(false);
            btnQuitar.setEnabled(false);
        } else {
            rol = (Rol) cmbRol.getSelectedItem();

            if (tableRol.getRowCount() == 0) {
                btnAsignar.setEnabled(true);
                btnQuitar.setEnabled(false);
            } else {
                for (int i = 0; i < tableRol.getRowCount(); i++) {
                    if (rol.getId_rol() == Integer.parseInt(tableRol.getValueAt(i, 0).toString())) {
                        btnAsignar.setEnabled(false);
                        btnQuitar.setEnabled(true);
                        break;
                    } else {
                        btnAsignar.setEnabled(true);
                        btnQuitar.setEnabled(false);
                    }
                }
            }
        }

    }//GEN-LAST:event_cmbRolItemStateChanged

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        usuarioui.mostrarPantalla();
    }//GEN-LAST:event_formInternalFrameClosing

    //Método para cargar datos en la tabla
    private void mostrarDatos(Usuario usuario) {
        try {
            DefaultTableModel modelo;
            FunUsuarioRol usuario_rol = new FunUsuarioRol();
            modelo = usuario_rol.mostrar(usuario);
            tableRol.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private void cargar_combo() {
        ArrayList<Rol> lista = funrol.mostrar_roles();

        cmbRol.setModel(valores_combo);
        valores_combo.addElement(new Rol(0, "Selecciona un rol"));

        for (Rol r : lista) {
            valores_combo.addElement(r);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<Rol> cmbRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tableRol;
    private javax.swing.JTextField txtIdUsuario;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
